UPDATE CLIENT c
SET name = 'MORA EM SANTA MARIA'
where c.CITY like 'SANTA MARIA';

DELETE
FROM PACKAGE p
where p.PAYMENT_METHOD_ID IS NULL;

SELECT *
FROM PAYMENT_METHOD
WHERE DUE_DAYS > 0;

SELECT *
FROM PAYMENT_METHOD
WHERE PARCELS > 1;

SELECT s.name, s.CNPJ, serv.name
FROM SUPPLIER s
         LEFT JOIN SERVICE serv ON s.id = serv.SUPPLIER_ID;

SELECT ex.id, TO_CHAR(ex.issue_date, 'dd/MM/YYYY') as issued, s.name
FROM EXPENSE ex
         JOIN SUPPLIER S on ex.SUPPLIER_ID = S.ID
WHERE ISSUE_DATE BETWEEN '06-11-2019' AND '06-12-2019';


ALTER TABLE SERVICE_TYPE
    ADD dummy VARCHAR(50);

ALTER TABLE SERVICE_TYPE
    MODIFY dummy VARCHAR(70) DEFAULT 'DUMMY VALUE';

UPDATE SERVICE_TYPE
SET SERVICE_TYPE.dummy = DEFAULT;

ALTER TABLE SERVICE_TYPE
    drop column dummy;
