
UPDATE CLIENT c SET name = 'MORA EM SANTA MARIA' where c.CITY like 'SANTA MARIA';

DELETE FROM PACKAGE p where p.PAYMENT_METHOD_ID IS NULL;

SELECT * FROM PAYMENT_METHOD WHERE DUE_DAYS > 0;

SELECT * FROM PAYMENT_METHOD WHERE PARCELS > 1;

SELECT s.name, s.CNPJ, serv.name FROM SUPPLIER s LEFT JOIN SERVICE serv ON s.id = serv.SUPPLIER_ID;