package DatabaseAccess.Model;


import java.sql.ResultSet;


public class Client extends Entity {

    @AutoGenerated
    public Long id;
    public String name;
    public String CPF_CNPJ;
    public String city;
    public String country;
    public String UF;
    public String address;
    public String phone;
    public String email;
    public String person_type;

    public Client(ResultSet result) {
        super(result);
    }

    public Client() {
    }

    @Override
    public String toString() {
        return "Client{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", CPF_CNPJ='" + CPF_CNPJ + '\'' +
                ", city='" + city + '\'' +
                ", country='" + country + '\'' +
                ", UF='" + UF + '\'' +
                ", address='" + address + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", person_type='" + person_type + '\'' +
                '}';
    }
}
