package DatabaseAccess.Model;


import DatabaseAccess.DatabaseConnection;
import DatabaseAccess.Tuple;
import DatabaseAccess.TypeMapping;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;


import java.sql.JDBCType;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Entity {


    public Entity(ResultSet result) {
        fillEntity(result);
    }

    public Entity() {

    }

    public void fillEntity(ResultSet result) {
        Field[] fields = this.getClass().getDeclaredFields();
        for (Field field : fields) {
            try {
                if (Modifier.isPublic(field.getModifiers()))
                    field.set(this, result.getObject(field.getName(), field.getType()));
            } catch (IllegalAccessException | SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public <T> T getSingle(int id, DatabaseConnection db) throws SQLException {
        String tableName = getClass().getName();
        String[] split = tableName.split("\\.");
        tableName = split[split.length - 1];
        ResultSet result = db.ExecuteQuery("SELECT * FROM " + tableName + " WHERE ID = ?",
                new Tuple[]{
                        new Tuple<Object, JDBCType>(id, JDBCType.INTEGER)
                });
        Entity e = null;
        result.next();
        try {
            e = getClass().getConstructor(ResultSet.class).newInstance(result);
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
            ex.printStackTrace();
        }
        db.CloseStatement(result.getStatement());
        return (T) e;
    }

    public <T> List<T> getAll(DatabaseConnection db) throws SQLException {
        String tableName = getClass().getName();
        String[] split = tableName.split("\\.");
        tableName = split[split.length - 1];
        ResultSet result = db.ExecuteQuery("SELECT * FROM " + tableName, null);
        List<T> entities = new ArrayList<>();
        while (result.next()) {
            try {
                entities.add((T) getClass().getConstructor(ResultSet.class).newInstance(result));
            } catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
                e.printStackTrace();
            }

        }
        db.CloseStatement(result.getStatement());
        return entities;
    }

    public <T> long insert(T e, String[] ignore, DatabaseConnection db) {
        String tableName = e.getClass().getName();
        String[] split = tableName.split("\\.");
        tableName = split[split.length - 1];
        List<Field> fields = new ArrayList(Arrays.asList(e.getClass().getFields()));
        if (ignore != null && ignore.length > 0) {
            List<String> ignoreList = new ArrayList(Arrays.asList(ignore));
            fields.removeIf(field -> ignoreList.contains(field.getName()));
        }
        fields.removeIf(field -> field.isAnnotationPresent(AutoGenerated.class));
        StringBuilder queryBuilder = new StringBuilder("INSERT INTO " + tableName + " (");
        for (Field field : fields) {
            queryBuilder.append(field.getName()).append(",");
        }
        queryBuilder.replace(queryBuilder.lastIndexOf(","), queryBuilder.lastIndexOf(",") + 1, "");
        queryBuilder.append(") VALUES(");
        for (Field field : fields) {
            queryBuilder.append("?,");
        }
        String query = queryBuilder.toString();
        query = query.substring(0, query.length() - 1) + ')';
        Tuple<Object, JDBCType>[] binds = new Tuple[fields.size()];


        for (int i = 0; i < fields.size(); i++) {
            Field field = fields.get(i);
            try {
                binds[i] = new Tuple<>(field.get(e), TypeMapping.getJDBCType(field.getType()));
            } catch (IllegalAccessException ex) {
                binds[i] = new Tuple<>(null, JDBCType.NULL);
            }
        }


        try {
            ResultSet r = db.Execute(query, binds);
            r.next();
            return Long.parseLong(r.getRowId(1).toString());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return -1;
    }

}
